### ISSUE TITLE
Storyboard enum cases should always be camelCase

### ISSUE THREAD

**Issue by aspyre** [krzyzanowskim/Natalie#93]
As per the Swift 3 guidelines, the enum cases should always start with a lowercase letter, rather than using the casing provided by the identifier.

**Comment by phimage** [comment]
Two things to do
- edit Parser and modify ReusableKind, SegueKind generated code with a lowercase letter
- edit Storyboard and look for `enum Segue`, to modify code which call `SwiftRepresentationForString`, to ask this function to set update the first letter to lowercase(there is already a `capitalizeFirstLetter` parameter that could be replaced by a clean enum firstLetter: .capitalize or .lowercase or .none by default )

I can do it if my PR #96 is merged, because I edit `SwiftRepresentationForString`, so a conflict will occurs

**Comment by aspyre** [comment]
Thank you!
